org: emacosmic
app: backend
service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment: 
    BUCKET_NAME: ${self:service}-public-photos-${sls:stage}
    PHOTOS_TABLE: ${self:service}-photos-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
          - "s3:*"
          Resource: "arn:aws:s3:::${self:service}-public-photos-${sls:stage}"
        - Effect: Allow
          Action: 
            - "rekognition:detectLabels"
          Resource: "*"
        - Effect: Allow
          Action: 
          - 'dynamodb:PutItem'
          - 'dynamodb:Get*'
          - 'dynamodb:Scan*'
          - 'dynamodb:Query'
          - 'dynamodb:UpdateItem'
          - 'dynamodb:DeleteItem'
          Resource: "arn:aws:dynamodb:::${self:service}-rekognition-photos-${sls:stage}"
resources: 
  Resources:
    PhotosTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ${self:service}-photos-${sls:stage}
          AttributeDefinitions:
            - AttributeName: primary_key
              AttributeType: S
          KeySchema:
            - AttributeName: primary_key
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

    PhotoBucket:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: ${self:service}-public-photos-${sls:stage}

        #Granting public aaccess to bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
    PhotoBucketAllowPublicReadPolicy:
     Type: AWS::S3::BucketPolicy
     Properties:
      Bucket: !Ref PhotoBucket
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Action: 
              - "s3:GetObject"
            Resource:
              - !Join ['/', [!GetAtt [PhotoBucket, Arn], '*']]
            Principal: "*"
            #AWS: "arn:aws:iam::YOUR_ACCOUNT_ID:user/YOUR_USER_NAME" -> iam only with auth to PutObject/GetObject
            Condition:
              Bool:
                aws:SecureTransport: 'true'

functions:
  savePhoto:
    handler: functions/savePhoto.savePhoto
    events:
      - httpApi:
          path: /
          method: post
  getPhotos:
    handler: functions/getPhotos.getPhotos
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline         
